import streamlit as st
import numpy as np
import cv2
from streamlit_image_comparison import image_comparison
from processing import ColorEngine
import ui

# Set page config globally first
st.set_page_config(page_title="GradeSense AI", page_icon=None, layout="wide", initial_sidebar_state="collapsed")

# Inject Custom CSS
ui.inject_custom_css()

# Helper to load image
def load_image(uploaded_file):
    if uploaded_file is None:
        return None
    file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
    image = cv2.imdecode(file_bytes, 1)
    if image is None:
        return None
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

def render_footer():
    st.markdown("---")
    st.markdown(
        """
        <div style='display: flex; justify-content: space-between; align-items: center; color: #555; padding: 10px 0;'>
            <div style="font-size: 0.8rem;">Generated by GradeSense AI | v2.0.1 Stable</div>
            <div style="font-size: 0.8rem;">All Systems Operational</div>
        </div>
        """, 
        unsafe_allow_html=True
    )

# -- PAGE DEFINITIONS --
# Functions must be defined before creating st.Page objects, 
# but st.Page objects must be created before running st.navigation

def home_page_func():
    # Home Screen Logic
    ui.render_header()
    st.markdown("---")
    st.markdown("<h3 style='text-align: center; margin-bottom: 40px;'>Select Your Workflow</h3>", unsafe_allow_html=True)
    
    c_home_1, c_home_2 = st.columns(2)
    
    with c_home_1:
        st.markdown("""
        <div class="glass-card" style="text-align: center; height: 220px;">
            <div style="width: 40px; height: 4px; background: linear-gradient(90deg, #7c3aed, #a855f7); margin: 0 auto 20px auto; border-radius: 2px;"></div>
            <h3>Emotion-to-Grade</h3>
            <p style='color: #9CA3AF; margin-bottom: 20px;'>Analyze palettes and generate cinematic 3D LUTs based on mood theory.</p>
        </div>
        """, unsafe_allow_html=True)
        if st.button("Launch Analyzer", key="btn_home_etg", use_container_width=True, type="primary"):
            st.switch_page(pg_emotion)

    with c_home_2:
        st.markdown("""
        <div class="glass-card" style="text-align: center; height: 220px;">
            <div style="width: 40px; height: 4px; background: linear-gradient(90deg, #2dd4bf, #0ea5e9); margin: 0 auto 20px auto; border-radius: 2px;"></div>
            <h3>Reference Mirror</h3>
            <p style='color: #9CA3AF; margin-bottom: 20px;'>Match the look of any reference image to your footage using AI sensing.</p>
        </div>
        """, unsafe_allow_html=True)
        if st.button("Launch Matcher", key="btn_home_rm", use_container_width=True, type="primary"):
            st.switch_page(pg_mirror)

    render_footer()

def emotion_engine_func():
    ui.render_header()
    if st.button("← Back to Dashboard"):
        st.switch_page(pg_home)
        
    st.markdown("## Emotion-to-Grade Engine")
    
    col_input, col_canvas = st.columns([1, 2])
    
    with col_input:
        uploaded_file = st.file_uploader("Upload Shot", type=["jpg", "png", "jpeg"])
        
        # Load image immediately if available
        image = None
        if uploaded_file:
            image = load_image(uploaded_file)
        
        if uploaded_file and image is not None:
            st.markdown("### Grading Intent")
            prompt = st.text_area(
                "Describe Cinematic Vision", 
                height=100, 
                placeholder="E.g. Warm 70s vintage look with soft contrast...", 
                key="ai_prompt"
            )
            
            analyze_clicked = st.button("Analyze Look", type="primary")
            
            # Session State Handling
            if analyze_clicked and prompt:
                 with st.spinner("AI Agent Developing Look..."):
                     # 1. Get Offsets
                     data = ColorEngine.prompt_to_numerical_offsets(prompt)
                     st.session_state.etg_data = data
                     
                     # 2. Get Colors for LUT Gen
                     colors = ColorEngine.get_dominant_colors(image, k=5)
                     # 3. Bake LUT Immediately using Full Params
                     # The 'data' dict already contains Lift, Gamma, Gain, Contrast, Sat, Midtones
                     lut_str = ColorEngine.create_3d_lut(colors, data)
                     st.session_state.etg_lut = lut_str
                     
                     # 4. Generate Predicted Palette
                     graded_hex = ColorEngine.apply_grade_to_palette(colors, data)
                     st.session_state.etg_palette_graded = graded_hex
            
            # Helper to clear if empty
            if not prompt and "etg_data" in st.session_state:
                del st.session_state.etg_data
                if "etg_lut" in st.session_state:
                    del st.session_state.etg_lut
                if "etg_palette_graded" in st.session_state:
                    del st.session_state.etg_palette_graded
    
    with col_canvas:
        if image is not None:
            st.image(image, caption="Source Input", use_container_width=True)
            
            # Default "Neutral" data if nothing analyzed yet
            active_data = st.session_state.get("etg_data", None)
            active_lut = st.session_state.get("etg_lut", None)
            graded_palette = st.session_state.get("etg_palette_graded", None)
            
            with st.spinner("Extracting Palette..."):
                colors = ColorEngine.get_dominant_colors(image, k=5)

            # Technical Scopes
            ui.render_scope_dashboard(image)

            # Analysis & Data
            st.markdown("### Palette & Insight")
            st.markdown("**Dominant Palette (Source)**")
            ui.render_swatches(colors)
            
            if graded_palette:
                st.markdown("**Predicted Grade Palette**")
                ui.render_swatches(graded_palette)
            
            if active_data:
                st.markdown("#### The 'Why' Behind the Grade")
                # Single big card for the explanation
                st.markdown(f"""
                <div class="glass-card">
                    <div style="color: #a855f7; font-weight: bold; margin-bottom: 5px;">AI CONSULTANT</div>
                    <p>{active_data['Explanation']}</p>
                </div>
                """, unsafe_allow_html=True)

                st.markdown("#### Industry Standard Offsets (Resolve)")
                rc1, rc2, rc3, rc4 = st.columns(4)
                with rc1: ui.draw_glass_card("Lift", f"{active_data['Lift']:+.2f}", "Shadows", "teal")
                with rc2: ui.draw_glass_card("Gamma", f"{active_data['Gamma']:+.2f}", "Midtones", "teal")
                with rc3: ui.draw_glass_card("Gain", f"{active_data['Gain']:+.2f}", "Highlights", "teal")
                with rc4: ui.draw_glass_card("Sat", f"{active_data['Sat']:.2f}", "Saturation", "teal")

                # LUT Generation (Direct Download)
                st.markdown("---")
                if active_lut:
                    # Clean filename from prompt query
                    safe_name = "".join([c for c in prompt.split()[0] if c.isalnum()])
                    ui.lut_download_section(active_lut, filename=f"GradeSense_{safe_name}.cube")
            else:
                st.info("Describe your desired look and click Analyze to generate a grade.")
        else:
             st.info("Upload an image to unlock the control surface.")
    
    render_footer()

def reference_mirror_func():
    ui.render_header()
    if st.button("← Back to Dashboard"):
        st.switch_page(pg_home)
        
    st.markdown("## Reference Mirror Engine")
    
    col_src, col_ref = st.columns(2)
    with col_src: src_file = st.file_uploader("Source (Your Clip)", type=["jpg", "png"])
    with col_ref: ref_file = st.file_uploader("Reference (The Look)", type=["jpg", "png"])
        
    if src_file and ref_file:
        source_img = load_image(src_file)
        reference_img = load_image(ref_file)
        
        if source_img is not None and reference_img is not None:
            # Dual Input
            c1, c2 = st.columns(2)
            with c1: st.image(source_img, caption="Source", use_container_width=True)
            with c2: st.image(reference_img, caption="Reference", use_container_width=True)
            
            # Source Scopes? Or Reference? Usually Reference is what we want to study.
            # Let's show Reference Scopes so user knows what they are aiming for.
            st.markdown("##### Reference Signal Analysis")
            ui.render_scope_dashboard(reference_img)
            
            st.markdown("### Process Control")
            if st.button("Run LAB Match Engine", type="primary", use_container_width=True):
                with st.spinner("Running Dual-Stream Smart Scaling & Histogram Matching..."):
                    try:
                        matched_img = ColorEngine.apply_color_match_smart(source_img, reference_img)
                        metrics = ColorEngine.calculate_grade_metrics(source_img, matched_img)
                        pro_offsets = ColorEngine.calculate_pro_offsets(source_img, reference_img)
                        advanced_advice = ColorEngine.analyze_advanced_grading(source_img, reference_img)

                        st.markdown("### Visual Verification")
                        image_comparison(
                            img1=source_img, img2=matched_img,
                            label1="Source", label2="Matched Result",
                            width=700, starting_position=50,
                            show_labels=True, make_responsive=True, in_memory=True
                        )
                        
                        st.markdown("### Match Intelligence")
                        mc1, mc2 = st.columns(2)
                        with mc1: ui.draw_glass_card("Match Accuracy", f"{metrics['PSNR']:.1f} dB", "Signal-to-Noise Ratio", "teal")
                        with mc2: ui.draw_glass_card("Structure Match", f"{1.0 - metrics['MSE']/255.0:.2f}", "Simulated Index", "teal")

                        ui.render_grading_consultant(pro_offsets)
                        ui.render_match_consultant(advanced_advice)
                        
                        st.markdown("### Delivery")
                        match_lut = ColorEngine.generate_match_lut(source_img, reference_img)
                        ui.lut_download_section(match_lut, filename="Rx_Match_Look.cube")
                        
                    except Exception as e:
                        st.error(f"Processing Error: {str(e)}")
    else:
        st.info("Awaiting Input Signals...")
    
    render_footer()

# -- MAIN ROUTING --
# Instantiate Page objects to be referenced for switching
pg_home = st.Page(home_page_func, title="Home", url_path="home", default=True)
pg_emotion = st.Page(emotion_engine_func, title="Emotion Engine", url_path="emotion")
pg_mirror = st.Page(reference_mirror_func, title="Reference Mirror", url_path="mirror")

pg = st.navigation(
    {
        "Main": [pg_home, pg_emotion, pg_mirror]
    },
    position="hidden"
)
pg.run()
